### ISSUE TITLE
Otter_scan

### ISSUE THREAD

**Issue by MurkFox** [knownsec/404StarLink2.0-Galaxy#1]
面向实战的WEB资产采集，支持masscan nmap输出数据，支持waf和cdn检测 后续会加入智能404识别以及敏感路径探测
项目地址：https://github.com/MurkFox/Otter_scan

**Comment by LoRexxar** [comment]
项目目前还是有点儿简单，比较有特色的几个点都有更成熟的项目了，还有很多维护的空间，需要有一些亮点出来，否则重复造轮子就没意义了
