### ISSUE TITLE
MDAT

### ISSUE THREAD

**Issue by Ch1ngg** [knownsec/404StarLink2.0-Galaxy#10]
### 项目名称
MDAT

### 项目链接
https://github.com/SafeGroceryStore/MDAT

### 项目简介
由于各种数据库攻击利用工具需要各种环境导致使用相当不便，便萌生了开发此工具的想法，将常用的数据库集合在一起并且优化当时工具的一些不足。

### 项目特点、亮点
集合了多种主流的数据库类型，跨平台使用，并且持续更新中

**Comment by LoRexxar** [comment]
星链计划不接受未开源的工具
