### ISSUE TITLE
BlackStone

### ISSUE THREAD

**Issue by thunderbarca** [knownsec/404StarLink2.0-Galaxy#12]
### 项目名称

黑石碑CTF竞赛平台

### 项目链接

https://github.com/thunderbarca/BlackStone

### 项目简介

 一个基于docker，开箱即用的CTF竞赛平台

### 项目特点、亮点
简单方便，可一键部署
基于docker，ctf题目可以相互独立

**Comment by LoRexxar** [comment]
这方面已经类似ctfd这类比较有名的开源项目，感觉本身还是不太有优势。

我注意到是django的架构写的，但是这类平台前端流量压力应该非常大，光靠django应该支撑不住，一般来说还需要nginx做反代，然后静态资源做优化，能做好的细节还是挺多的。

**Comment by thunderbarca** [comment]
相比于CTFD优势的化的确也就是本土化做的比较好，部署简单了，至于nginx那是部署方面的问题，后期会补充文档

**Comment by LoRexxar** [comment]
当然，提到部署的问题是因为文档中没有提及这方面，可能使用者就会直接跑起来用

**Comment by thunderbarca** [comment]
生产部署文档整理好了

**Comment by LoRexxar** [comment]
我想问下，这个题目自动启用，是只能在当前宿主机启动吗，那这个假设一个题目起几百个docker怎么办，宿主机还撑得住吗

**Comment by thunderbarca** [comment]
是的 现在只能在当前宿主机用，如果你说的情况可能要考虑集群化或者是分布式方案了

**Comment by LoRexxar** [comment]
不是集群化的问题吧，那正常就有几百队参加，那不就是几百个docker同时存在吗
