### ISSUE TITLE
javaSerializationTools

### ISSUE THREAD

**Issue by potats0** [knownsec/404StarLink2.0-Galaxy#13]
### 项目名称

javaSerializationTools

### 项目链接

https://github.com/potats0/javaSerializationTools

### 项目简介

使用python 读写java反序列化文件

### 项目特点、亮点

1. 解析java反序列化文件
2. 可以不按规定 生成java反序列化文件

**Comment by LoRexxar** [comment]
感觉还不错，但是文档不完整呀

**Comment by potats0** [comment]
我在补，这就push
