### ISSUE TITLE
WhetherMysqlSham   识别Mysql蜜罐

### ISSUE THREAD

**Issue by BeichenDream** [knownsec/404StarLink2.0-Galaxy#16]
### WhetherMysqlSham   判断数据库是否是蜜罐

[WhetherMysqlSham]

### 项目链接

https://github.com/BeichenDream/WhetherMysqlSham

### 项目简介

检测目标Mysql数据库是不是蜜罐,获取目标数据库详细信息

### 项目特点、亮点

在渗透中经常遇到蜜罐 使用此工具可排除被蜜罐捕捉的风险

详情介绍 https://mp.weixin.qq.com/s?__biz=MzIzMTc1MjExOQ==&mid=2247493202&idx=1&sn=f47acca7e0a4b85bbd7eaf9e7fc80735&chksm=e89dce8adfea479c4fc31bb63f111245b841568c2527f075167d72f0983db4a1dfe4b5620997&mpshare=1&scene=23&srcid=0129b4nb4ZwoBNEc60y7PXtL&sharer_sharetime=1611903086462&sharer_shareid=2842013f28b5e4d016712aee69d880d9#rd

**Comment by BeichenDream** [comment]
已编译版本 

https://github.com/BeichenDream/WhetherMysqlSham/releases/tag/v1.0

**Comment by LoRexxar** [comment]
收录入第四期
