### ISSUE TITLE
f8x

### ISSUE THREAD

**Issue by No-Github** [knownsec/404StarLink2.0-Galaxy#17]
### 项目名称

f8x

### 项目链接

- [ffffffff0x/f8x](https://github.com/ffffffff0x/f8x)

### 项目简介

红/蓝队环境自动化部署工具,支持多种场景,渗透,开发,代理环境,服务可选项等

### 项目特点、亮点

1. 大多数场景下，在不同的云购买一些vps服务器用于部署红/蓝队设施，不能做到开箱即用，使用此工具可以快速部署所需要的各类服务。
2. 兼顾到本地VM虚拟机的需求，可以选择走socket代理进行安装，Proxychains-ng也会自动安装，只需配置好Proxychains-ng配置。
3. 基本兼容 CentOS、Debian、Fedora、Ubuntu 等衍生系统，以 -all 选项为例
	- [CentOS 7 效果展示](https://asciinema.org/a/387124)
	- [Debian 10 效果展示](https://asciinema.org/a/387123)
	- [Fedora 33 效果展示](https://asciinema.org/a/387128)
	- [Ubuntu 20.10 效果展示](https://asciinema.org/a/387127)
4. 后续开发计划
	- 补充蜜罐的部署
	- 再部署CS时集成一些CS插件
	- 完善信息收集模块，辅助提权

**Comment by LoRexxar** [comment]
感觉挺不错的，可以加一下我的微信，然后后续再和你沟通

**Comment by LoRexxar** [comment]
收录入第四期
