### ISSUE TITLE
BerylEnigma

### ISSUE THREAD

**Issue by RyuZUSUNC** [knownsec/404StarLink2.0-Galaxy#18]
### 项目名称

BerylEnigma

### 项目链接

[ffffffff0x/BerylEnigma](https://github.com/ffffffff0x/BerylEnigma)

### 项目简介

一个主要服务于渗透测试过程中的加解密与编解码的小工具包。

### 项目特点、亮点

1. UI 简洁明了，使用方便快速。
2. UI 操作类与具体实现类拆分，可以快速调用。

**Comment by LoRexxar** [comment]
还是有点儿简单啊，这个东西我见过不少，也有常用的

**Comment by RyuZUSUNC** [comment]
> 还是有点儿简单啊，这个东西我见过不少，也有常用的

是的，目前只优先完成了最基础的功能，之后逐步扩展加密方法以及如加密字典生成一类的更多功能。如果觉得目前太简单的话，在项目更加完善后我再来提交吧。

**Comment by LoRexxar** [comment]
嗯哼，目前还是有点儿简单，持续维护的话，还是有机会入选噢~
