### ISSUE TITLE
vscode-maudit

### ISSUE THREAD

**Issue by m4yfly** [knownsec/404StarLink2.0-Galaxy#19]
### 项目名称

vscode-maudit

### 项目链接

https://github.com/m4yfly/vscode-maudit

### 项目简介

基于正则的代码审计辅助工具

### 项目特点、亮点

* 以vscode插件形式提供，开箱即用，跨平台。
* 基于typescript实现，扫描速度相比于其它工具更快。
* 整合部分开源项目中的部分匹配规则，主要针对php，还有部分针对python和java。

**Comment by LoRexxar** [comment]
我翻了翻。。单靠正则不行啊，这个肯定误报特别多，太简单了呀
