### ISSUE TITLE
frida-skeleton

### ISSUE THREAD

**Issue by Margular** [knownsec/404StarLink2.0-Galaxy#2]
本项目是基于frida写了一个方便编写frida hook安卓js脚本的框架，frida-skeleton会根据指定的正则表达式持续监听并hook对应的程序，遍历scripts目录下和projects目录下的所有js文件并将它们全部加载用以hook这些程序，项目地址：https://github.com/Margular/frida-skeleton

详细介绍：https://wiki.margular.com/zh/frida-skeleton
用法简介：https://wiki.margular.com/zh/frida-skeleton/usage

**Comment by LoRexxar** [comment]
感觉挺不错的，能不能麻烦微信联系一下我

**Comment by LoRexxar** [comment]
close in 2th
