### ISSUE TITLE
Doge-Assembly

### ISSUE THREAD

**Issue by timwhitez** [knownsec/404StarLink2.0-Galaxy#20]
### 项目名称

Doge-Assembly

### 项目链接

https://github.com/timwhitez/Doge-Assembly

### 项目简介

使用Golang execute assembly加载C#程序

C#程序编译为静态资源文件，使用AES加密

clr.dll进程注入的过程采用direct syscall进行api调用

### 项目特点、亮点

多种免杀方式集合起来，C#好用的红队工具较多。

**Comment by LoRexxar** [comment]
目前的感觉是，有点儿像https://github.com/TheWover/donut。

好像没有明显的优势或者创新点

**Comment by timwhitez** [comment]
可能优势就是免杀方面了，用到了direct syscall，别的需要花时间再考虑一下使用中的需求
