### ISSUE TITLE
CodeReviewTools

### ISSUE THREAD

**Issue by Ppsoft1991** [knownsec/404StarLink2.0-Galaxy#21]
### 项目名称

CodeReviewTools

### 项目链接

https://github.com/Ppsoft1991/CodeReviewTools

### 项目简介

快速批量反编译特定Jar包中的class名称

### 项目特点、亮点

search模式可以使用正则搜索文件夹下jar包中的class （场景:知道class名不知道具体位置，想寻找所有Controller接口 等等）
war模式，直接反编译war包，快速投入代码审计的工作
all模式，搜索jar包中符合groupid的class，解压此jar包（场景:很多项目会将自己写的类库编译成jar包，混在一起很难区分反编译。如websphere，想反编译所有关于websphere的jar包，只需要指定目录，设置好websphere的groupid即可）

**Comment by LoRexxar** [comment]
你这个东西我感觉有点儿意思的，后续到收录的时候我再联系你

**Comment by LoRexxar** [comment]
合入5th
