### ISSUE TITLE
linglong无法登录

### ISSUE THREAD

**Issue by WinonaForever** [knownsec/404StarLink2.0-Galaxy#23]
![image](https://user-images.githubusercontent.com/52448982/113690786-5bbe7480-96fe-11eb-8694-cd8f7741859c.png)
![image](https://user-images.githubusercontent.com/52448982/113690847-6f69db00-96fe-11eb-8acc-94a18093327e.png)
![image](https://user-images.githubusercontent.com/52448982/113690908-7ee92400-96fe-11eb-8d1c-679db0fe3abc.png)

**Comment by LoRexxar** [comment]
铁子，issue发在项目下噢，不要发在这里，帮不了你
