### ISSUE TITLE
Stowaway

### ISSUE THREAD

**Issue by ph4ntonn** [knownsec/404StarLink2.0-Galaxy#25]
### 项目名称

Stowaway

### 项目链接

https://github.com/ph4ntonn/Stowaway

### 项目简介

Stowaway旨在构建多级网络，将流量通过多种方式“偷渡”至核心网络

### 项目特点、亮点

在实际行动过程中，渗透测试者往往会遇到网段不通，无法直接访问核心网络等一系列问题

Stowaway正是为了解决这个问题而写，方便渗透测试人员通过多级跳跃，从外部dmz等一系列区域逐步深入核心网络

同时Stowaway也不仅仅只是一个流量转发工具，其中也嵌入了不少专为渗透测试人员所用的功能，例如端口复用、ssh隧道，流量伪装等等

详情也可查看repo的README～

**Comment by 0x7Fancy** [comment]
项目很赞，加入到星链第七期(2021.7)；麻烦你添加下 README 末尾我的个人微信(标注下 "Stowaway作者")，后续我们拉你入群并进行后续的沟通
