### ISSUE TITLE
Multiple Database Utilization Tools

### ISSUE THREAD

**Issue by Ch1ngg** [knownsec/404StarLink2.0-Galaxy#26]
### 项目名称
MDUT - Multiple Database Utilization Tools

### 项目链接
https://github.com/SafeGroceryStore/MDUT

### 项目简介
MDUT 全称 Multiple Database Utilization Tools，是一款中文的数据库跨平台利用工具，集合了多种主流的数据库类型。基于前人 SQLTOOLS 的基础开发了这套程序(向 SQLTOOLS 致敬)，旨在将常见的数据库利用手段集合在一个程序中，打破各种数据库利用工具需要各种环境导致使用相当不便的隔阂。

### 项目特点、亮点
工具以 JAVAFx 作为 GUI 操作界面，界面美观。同时程序还支持多数据库同时操作，每种数据库都相互独立。跨平台支持，极大方便了网络安全工作者的使用。

**Comment by 0x7Fancy** [comment]
项目很赞，加入到星链第七期(2021.7)；麻烦你添加下 README 末尾我的个人微信(标注下 "MDUT作者")，后续我们拉你入群并进行后续的沟通
