### ISSUE TITLE
openstar

### ISSUE THREAD

**Issue by starjun** [knownsec/404StarLink2.0-Galaxy#27]
### 项目名称
openstar

### 项目链接

https://github.com/starjun/openstar

### 项目简介
基于openresty 开发的 waf ,规则类 waf 

### 项目特点、亮点
支持复杂规则描述等...

**Comment by 0x7Fancy** [comment]
项目很赞，加入到星链第七期(2021.7)；麻烦你添加下 README 末尾我的个人微信(标注下 "openstar作者")，后续我们拉你入群并进行后续的沟通
