### ISSUE TITLE
HackBrowserData

### ISSUE THREAD

**Issue by moonD4rk** [knownsec/404StarLink2.0-Galaxy#3]
hack-browser-data 是一个解密浏览器数据（密码|历史记录|Cookies|书签）的导出工具，支持全平台主流浏览器的数据导出窃取。

项目地址：https://github.com/moonD4rk/HackBrowserData

**Comment by LoRexxar** [comment]
很棒的工具，能不能麻烦微信联系一下我

**Comment by LoRexxar** [comment]
close in 2th
