### ISSUE TITLE
Awvs14 Docker

### ISSUE THREAD

**Issue by ran-xing** [knownsec/404StarLink2.0-Galaxy#35]
### 项目名称

[AWVS14 Docker]

### 项目链接

[https://github.com/XRSec/AWVS14-Docker]

### 项目简介

[A new Acunetix Premium update has been released for Windows, Linux, and macOS: 14.4.210816098.
作为一款经典的商业扫描器，深受广大白帽子的欢迎和喜爱
作者只是在方便快捷的同时，做了个更新]

### 项目特点、亮点

[Docker编译采用了一站式生成，除了原版安装包和激活码，保证无后门，所有编译过程都在Github仓库里面，同时，希望二开的兄弟注明一下作者！]

**Comment by 0x7Fancy** [comment]
未找到原始仓库，closed
