### ISSUE TITLE
Goby-Docker

### ISSUE THREAD

**Issue by ran-xing** [knownsec/404StarLink2.0-Galaxy#36]
### 项目名称

[Goby-Docker]

### 项目链接

[https://github.com/XRSec/Goby-Docker]

### 项目简介

[作为一款ATTCK工具，在20年HVV大放光彩，本Docker容器仅仅为了方便快捷，同时支持自动更新，但是需要从Github下载]

### 项目特点、亮点

[容器采用一站式部署，无人工干预，全部编译过程在Github仓库可见，杜绝后门]

**Comment by 0x7Fancy** [comment]
未找到原始仓库，closed
