### ISSUE TITLE
GShark

### ISSUE THREAD

**Issue by madneal** [knownsec/404StarLink2.0-Galaxy#4]
### 项目名称

GShark

### 项目链接

https://github.com/madneal/gshark

### 项目简介

一款开源敏感信息监测系统，可以监测包括 github、gitlab（目前不太稳定，由于gitlab对于免费用户不提供代码全文检索API）、searchcode 多平台的敏感信息监测。

### 项目特点、亮点

* 支持多个来源，不限于 github
* 基于 golang 编写，支持跨平台
* 优化了结果保存，减少误报
* 集成 server 酱，监测结果实时通知
* 坚持维护吧

**Comment by LoRexxar** [comment]
还挺不错的，麻烦可以微信联系一下我吗

**Comment by LoRexxar** [comment]
close in 2th
