### ISSUE TITLE
【自荐】命令行鼠标交互式的方式去管理 K8s - lazykube

### ISSUE THREAD

**Issue by elfgzp** [knownsec/404StarLink2.0-Galaxy#6]
### 项目链接

[https://github.com/TNK-Studio/lazykube](https://github.com/TNK-Studio/lazykube)

### 项目简介

命令行鼠标交互式的方式去管理 K8s

### 项目特点、亮点

命令行鼠标交互式的方式去管理 K8s，对比 k9s 命令行工具，可以不用去记那么多快捷键，直接用鼠标交互操作。主要解决公司不使用 rancher 和 dashboard 管理 K8s，只能通过堡垒机访问，这样操作方式只有终端，节约敲命令的时间。

**Comment by LoRexxar** [comment]
抱歉，不太能算是安全行业相关，不能予以收录
