### ISSUE TITLE
HaE

### ISSUE THREAD

**Issue by gh0stkey** [knownsec/404StarLink2.0-Galaxy#7]
### 项目名称

HaE

### 项目链接

https://github.com/gh0stkey/HaE

### 项目简介

HaE是基于 BurpSuite 插件 JavaAPI 开发的请求高亮标记与信息提取的辅助型插件，该插件可以通过自定义正则的方式匹配响应报文或请求报文，可以自行决定符合该自定义正则匹配的相应请求是否需要高亮标记、信息提取。

### 项目特点、亮点

BurpSuite是一款安全从业者常用工具，大部分的Web安全测试都基于该工具，但流量多而杂的场景下，去做测试不免会浪费很多时间去一个一个的针对性看请求，借助HaE插件可以有效的减少测试的时间，以高亮的方式标记出你所需要的请求或响应，高效的进行漏洞挖掘和测试。

**Comment by LoRexxar** [comment]
工具本身还是有亮点的，但是我注意到并没有公开很多规则，如果没有足够的规则的话，这个插件本身就变得有些普通了。如果可以的话，最好可以公开更多的规则

**Comment by gh0stkey** [comment]
最近设立了一个公开规则库网站：https://gh0st.cn/HaE/

**Comment by LoRexxar** [comment]
这个我看到了，但还是很少呀。毕竟从使用的角度来说，这个插件的亮点主要还是集中在规则上，如果没有足够的规则，自己去慢慢添加的话，使用起来也很不方便吧

**Comment by gh0stkey** [comment]
是的，规则这一块，想的是把一些指纹的批量转换；目前还在计划中，除此之外，自定义也是一个亮点，可以在渗透中使用HaE提取自己需要的，比如说我有一个接口想要提取里面的所有用户名，一切都可以基于HaE去操作。

**Comment by LoRexxar** [comment]
如果仅仅是用来正则匹配返回包的话，就觉得还是太简单了。所以我说你这个项目的亮点应该是规则

**Comment by gh0stkey** [comment]
嗯嗯，后面会加速公共规则的推动。

**Comment by gh0stkey** [comment]
已经更新了公共规则库，添加红队重点攻击系统指纹【360, CISCO, Citrix, exchange, H3C, jira, juniper, Nagios, Spark, TP-LINK, vpn, zabbix, 万户, 华为, 泛微, 深信服, 绿盟, 致远, 蓝凌, 通达, 金和, 金蝶, 阿里云】
