### ISSUE TITLE
群二维码不展示，能否更新一下

### ISSUE THREAD

**Issue by zengxiangjiang** [knownsec/404StarLink2.0-Galaxy#8]
群二维码不展示，能否更新一下

**Comment by LoRexxar** [comment]
我的微信扫不了吗，群二维码不能用了，因为超过200人了

**Comment by zengxiangjiang** [comment]
还有其他入群方式吗

**Comment by LoRexxar** [comment]
> 还有其他入群方式吗

没办法了，只能加我的微信，我拉你进去，微信就是这样，很辣鸡

**Comment by zengxiangjiang** [comment]
您的微信号是多少？0.0

**Comment by LoRexxar** [comment]
你看不到吗，最下面有二维码

**Comment by zengxiangjiang** [comment]
对，展示不出来

**Comment by LoRexxar** [comment]
![image](https://user-images.githubusercontent.com/12526901/104534713-c310df00-564f-11eb-930c-f738b222a122.png)

这样呢
